import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import NewUrlForm from '@/components/NewUrlForm';
import clientPromise from '@/app/utils/mongodb';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Url smashr',
  description: 'Generated by create next app',
};

const links = [
  { href: '/', label: 'Home' },
  { href: '/docs', label: 'Docs' },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100`}>
        <header>
          <nav>
            <ul className="flex flex-row">
              {links.map((link) => (
                <li key={link.href} className="p-4">
                  <Link href={link.href}>{link.label}</Link>
                </li>
              ))}
            </ul>
          </nav>
          <h1>Url shortener</h1>
          <NewUrlForm />
        </header>
        {children}
      </body>
    </html>
  );
}
