import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Url smashr',
  description: 'Generated by create next app',
};

const links = [
  { href: '/', label: 'Home' },
  { href: '/todos', label: 'Todos' },
  { href: '/docs', label: 'Docs' },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header>
          <nav>
            <ul className='flex flex-row'>
              {links.map((link) => (
                <li key={link.href} className='p-4'>
                  <Link href={link.href}>{link.label}</Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
