import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import NewUrlForm from '@/components/NewUrlForm';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Url smashr',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-900`}>
        <header>
          <h1>Url shortener</h1>
        </header>
        <NewUrlForm />
        {children}
      </body>
    </html>
  );
}
